-- 도서를 주문하지 않은 고객을 알고 싶다

-- 주매하지 않은 고객 = 모든 고객 - 도서를 주문한 고객

SELECT
    NAME
FROM
    CUSTOMER MINUS
    SELECT
        NAME
    FROM
        CUSTOMER
    WHERE
        CUSTID IN (
            SELECT
                CUSTID
            FROM
                ORDERS
        );

-- 주문이 있는 고객의 이름과 주소를 조회하시오

SELECT
    NAME,
    ADDRESS
FROM
    CUSTOMER C
WHERE
    EXISTS (
        SELECT
            *
        FROM
            ORDERS   O
        WHERE
            O.CUSTID = C.CUSTID
    );

-- 데이터 정의어: DDL

CREATE TABLE NEWBOOK (
    BOOKID NUMBER NOT NULL,
    BOOKNAME VARCHAR2(20) NOT NULL,
    PUBLISHER VARCHAR2(20) UNIQUE,
    PRICE NUMBER DEFAULT 10000 CHECK(PRICE>1000),
    PRIMARY KEY (BOOKID, PUBLISHER)
);

CREATE TABLE NEWCUSTOMER (
    CUSTID NUMBER PRIMARY KEY,
    NAME VARCHAR2(40),
    ADDRESS VARCHAR2(40),
    PHONE VARCHAR2(40)
);

CREATE TABLE NEWORDERS (
    ORDERID NUMBER,
    CUSTID NUMBER NOT NULL,
    BOOKID NUMBER NOT NULL,
    SALEPRICE NUMBER,
    ORDERDATE DATE,
    PRIMARY KEY (ORDERID),
    FOREIGN KEY (CUSTID) REFERENCES NEWCUSTOMER(CUSTID) ON DELETE CASCADE
);

ALTER TABLE NEWBOOK ADD ISBN VARCHAR2(13);
ALTER TABLE NEWBOOK MODIFY ISBN NUMBER;
ALTER TABLE NEWBOOK DROP COLUMN ISBN;

ALTER TABLE NEWBOOK ADD PRIMARY KEY(BOOKID);

DROP TABLE NEWBOOK;
DROP TABLE NEWCUSTOMER;
DROP TABLE NEWORDERS;

INSERT INTO BOOK(BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES(11, '스포츠의학', '한솔의학서적', 90000);

SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;

UPDATE CUSTOMER SET ADDRESS = '대한민국 부산' WHERE CUSTID = 5;