DROP TABLE NOTICE;

CREATE TABLE NOTICE (
    BNO NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT BLOB NOT NULL,
    WRITER VARCHAR2(20) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    VIEWCOUNT NUMBER DEFAULT 0,
    CONSTRAINT NOTICE_PK PRIMARY KEY (BNO)
);

COMMIT;