CREATE TABLE MEMBER (
    BNO NUMBER NOT NULL,
    NAME VARCHAR2(40) NOT NULL,
    NICKNAME VARCHAR2(40) NOT NULL,
    ID VARCHAR2(40) NOT NULL,
    PW VARCHAR2(500) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PROFILEIMG VARCHAR2(200),
    CONSTRAINT MEMBER_PK PRIMARY KEY (BNO)
);

CREATE SEQUENCE MEMBER_SEQ;

COMMIT;