SELECT * FROM NOTICE;

DROP TABLE NOTICE;

CREATE SEQUENCE NOTICE_SEQ;

DROP SEQUENCE NOTICE_SEQ;

DELETE NOTICE;

INSERT INTO NOTICE VALUES (NOTICE_SEQ.NEXTVAL, '제목입니다', '내용입니다', '관리자', SYSDATE, 0);

CREATE TABLE NOTICE (
    BNO NUMBER(3) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    WRITER VARCHAR2(20) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    VIEWCOUNT NUMBER(3) DEFAULT 0
);

COMMIT;