CREATE TABLE P1_USERS (
    UNO NUMBER NOT NULL,
    UNAME VARCHAR2(40) NOT NULL,
    PW VARCHAR2(500) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PROFILEIMG VARCHAR2(200),
    CONSTRAINT P1_USERS_PK PRIMARY KEY (UNO)
);

CREATE SEQUENCE UNO_SEQ;

