CREATE TABLE LITEACCOUNT (
    ACCOUNTTYPE VARCHAR2(6) DEFAULT '일반',
    ACCOUNTNUM NUMBER(5) NOT NULL PRIMARY KEY,
    OWNERNAME VARCHAR2(30) NOT NULL,
    PASSWORD NUMBER(2) NOT NULL,
    BALANCE NUMBER(15)
);

INSERT INTO LITEACCOUNT (
    ACCOUNTNUM,
    OWNERNAME,
    PASSWORD,
    BALANCE
) VALUES (
    11111,
    '케이드',
    11,
    100000
);

select * from liteaccount;

delete liteaccount where ACCOUNTNUM = 16996; 