SELECT * FROM (SELECT
ROWNUM RN, A.BNO, A.TITLE, B.CONTENT
FROM FAQ1 A LEFT JOIN FAQ2 B ON A.BNO = B.QNO
WHERE ROWNUM <= ?
ORDER BY A.BNO DESC) WHERE RN > 0;

SELECT COUNT(BNO) AS CNT FROM FAQ1;

SELECT * FROM (
SELECT /*+ INDEX_DESC (PORTFOLIO PORT_PK) */ 
ROWNUM RN, BNO, TITLE, CONTENT, IMGURL, REGDATE, VIEWCOUNT
FROM PORTFOLIO WHERE ROWNUM <= 10 ORDER BY BNO DESC
) WHERE RN > 0;