CREATE TABLE TBL_STUDENT (
    SYEAR CHAR(1) NOT NULL,
    SCLASS CHAR(2) NOT NULL,
    SNO CHAR(2) NOT NULL,
    SNAME VARCHAR2(20),
    BIRTH CHAR(8),
    GENDER CHAR(1),
    TE11 CHAR(3),
    TE12 CHAR(4),
    TE13 CHAR(4)
);

ROLLBACK;