-- 넌 학생이고...
CREATE TABLE TBL_STUDENT (
    SYEAR CHAR(1) NOT NULL,
    SCLASS CHAR(2) NOT NULL,
    SNO CHAR(2) NOT NULL,
    SNAME VARCHAR2(20),
    BIRTH CHAR(8),
    GENDER CHAR(1),
    TE11 CHAR(3),
    TE12 CHAR(4),
    TE13 CHAR(4),
    CONSTRAINT PK_STUDENT PRIMARY KEY (SYEAR, SCLASS, SNO)
);

-- ...난 교사야.
CREATE TABLE TBL_DEPT (
    SYEAR CHAR(1) NOT NULL,
    SCLASS CHAR(2) NOT NULL,
    TNAME VARCHAR2(20),
    CONSTRAINT PK_TDEPT PRIMARY KEY (SYEAR, SCLASS)
);

-- 그리고 난 성적이다옹!
CREATE TABLE TBL_SCORE (
    SYEAR CHAR(1),
    SCLASS CHAR(2),
    SNO CHAR(2),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3),
    CONSTRAINT FK_SCORE FOREIGN KEY (SYEAR, SCLASS, SNO) REFERENCES TBL_STUDENT(SYEAR, SCLASS, SNO)
 -- 이 테이블의 학년, 반, 번호는 반드시 TBL_STUDENT에 존재하는 학년, 반, 번호여야 한다.
 -- 즉 이 두 테이블 사이엔 연관관계가 있다는 것.
 -- 하나의 레코드에 하나의 레코드씩만 연관됨: 1:1 연관관계
);

DROP TABLE TBL_STUDENT;

ALTER TABLE TBL_STUDENT RENAME COLUMN TE13 TO TEL3;

ROLLBACK;

COMMIT;