SELECT
    *
FROM
    NOTICE
ORDER BY
    BNO DESC;

ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_PK PRIMARY KEY (BNO);

SELECT /*+ INDEX_DESC (NOTICE NOTICE_PK) */
    *
FROM
    NOTICE;

SELECT /*+ INDEX_ASC (NOTICE NOTICE_PK) */
    ROWNUM RN,
    BNO,
    TITLE
FROM
    NOTICE;

SELECT /*+ INDEX_DESC (NOTICE NOTICE_PK) */ ROWNUM RN, BNO, TITLE
FROM NOTICE
WHERE ROWNUM <= 10;

SELECT *
FROM (
    SELECT /*+ INDEX_DESC (NOTICE NOTICE_PK) */ ROWNUM RN, BNO, TITLE, CONTENT, WRITER, REGDATE, VIEWCOUNT
    FROM NOTICE
    WHERE ROWNUM <= 2 * 10
)
WHERE RN > (2 - 1) * 10;